In [2]:
import numpy as np

import sys 
sys.path.append("../General_Functions/")

from Flow_functions import *

In [3]:
x = np.array([1.0,0,3.0])
x /= np.linalg.norm(x)
print(x)
n = np.array([1.0,0,6.0])
n /= np.linalg.norm(n)
grad = StrainStresslet # Note: it should work with a strain or another flow
grad_name = 'StrainStresslet'
e = np.array([0, 0, 1])

[0.31622777 0.         0.9486833 ]


In [4]:
StrainStresslet(e,x)

array([[ 0.65, -0.  , -2.25],
       [-0.  ,  1.7 , -0.  ],
       [-2.25, -0.  , -2.35]])

In [5]:
GradientStresslet(e,x)

array([[ 0.65, -0.  , -1.35],
       [-0.  ,  1.7 , -0.  ],
       [-3.15, -0.  , -2.35]])

In [6]:
StrainStokeslet(e,x)

array([[ 0.66407831, -0.        , -0.85381497],
       [-0.        ,  0.9486833 , -0.        ],
       [-0.85381497, -0.        , -1.61276161]])